"""hotfix

Revision ID: 1341035aa44e
Revises: 667b9ca05074
Create Date: 2019-03-15 15:23:21.378918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1341035aa44e'
down_revision = '667b9ca05074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.alter_column('flights', '_to',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=True)
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    # ### end Alembic commands ###
