"""removed planes

Revision ID: 318ae6b43cec
Revises: 02d6e326cbf8
Create Date: 2019-03-25 15:07:42.671299

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '318ae6b43cec'
down_revision = '02d6e326cbf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('flights_ibfk_1', 'flights', type_='foreignkey')
    op.drop_table('planes')

    op.drop_column('flights', 'plane_id')
    # op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.add_column('flights', sa.Column('plane_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('flights_ibfk_1', 'flights', 'planes', ['plane_id'], ['id'], ondelete='CASCADE')
    op.create_table('planes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('manufacturer', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('model', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('biz_seats_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('econom_seats_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('vip_seats_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
