"""upd2

Revision ID: a0ddeeed01a2
Revises: f93ad73585b3
Create Date: 2019-02-26 18:40:37.967650

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0ddeeed01a2'
down_revision = 'f93ad73585b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=50), index=True, unique=True))
    op.alter_column('users', 'first_name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    #op.drop_index('ix_users_first_name', table_name='users')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_first_name', 'users', ['first_name'], unique=True)
    op.alter_column('users', 'first_name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
