"""upd3
Revision ID: ebd5e4d3d047
Revises: a0ddeeed01a2
Create Date: 2019-02-26 20:10:01.868486
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ebd5e4d3d047'
down_revision = 'a0ddeeed01a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'first_name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    #op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # op.drop_index('ix_users__username', table_name='users')
    # op.drop_column('users', '_username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_username', mysql.VARCHAR(length=50), nullable=True))
    op.create_index('ix_users__username', 'users', ['_username'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###